const fs = require('fs');

// Patch TermsOfService.tsx
let tosCode = fs.readFileSync('src/components/TermsOfService.tsx', 'utf8');

const newTosSections = `  const sections = [
    {
      id: "eligibility",
      title: "Eligibility",
      content: (
        <p>
          By using this Service, you represent and warrant that you are at least 13 years of age (or the age of majority in your jurisdiction) and have the full legal authority to enter into these Terms. If you are under the age of majority, you must have your parent or legal guardian's permission to use the Service.
        </p>
      )
    },
    {
      id: "user-accounts",
      title: "User Accounts",
      content: (
        <>
          <p>
            When you create an account with us, you must provide accurate, complete, and current information. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account on our Service.
          </p>
          <ul className="list-disc pl-5 mt-4 space-y-2 text-[#8a8a8a]">
            <li>You are responsible for safeguarding the password and PINs that you use to access the Service and for any activities or actions under your password.</li>
            <li>You agree not to disclose your password or PINs to any third party.</li>
            <li>You must notify us immediately upon becoming aware of any breach of security or unauthorized use of your account.</li>
          </ul>
        </>
      )
    },
    {
      id: "intellectual-property",
      title: "Intellectual Property",
      content: (
        <>
          <p>
            The Service and its original content, features, and functionality (excluding AI-generated code produced for your projects) are and will remain the exclusive property of Atmos Orbit and its licensors. Our trademarks and trade dress may not be used in connection with any product or service without our prior written consent.
          </p>
          <p>
            <strong>Generated Code & Assets:</strong> Any code, scripts (such as Luau), or integrated assets generated by Atmos Orbit in response to your prompts belong to you, subject to Roblox's terms of service and the licensing of any third-party Creator Marketplace assets fetched by the tool.
          </p>
        </>
      )
    },
    {
      id: "prohibited-uses",
      title: "Prohibited Uses",
      content: (
        <p>
          You agree not to use the Service: (a) in any way that violates any applicable national or international law or regulation; (b) for the purpose of exploiting, harming, or attempting to exploit or harm minors in any way; (c) to generate malicious code, exploits, or scripts designed to harm, disrupt, or gain unauthorized access to Roblox games or servers; or (d) to impersonate or attempt to impersonate Atmos Orbit, an employee, another user, or any other person or entity.
        </p>
      )
    },
    {
      id: "contact-us",
      title: "Contact Us",
      content: (
        <p>
          If you have any questions about these Terms, please contact us at legal@atmosorbit.com.
        </p>
      )
    }
  ];`;

// extract from "  const sections = [" to "  ];"
const tosStart = tosCode.indexOf('  const sections = [');
const tosEnd = tosCode.indexOf('  ];\n\n  return (', tosStart) + 4;

if (tosStart !== -1 && tosEnd !== -1) {
  tosCode = tosCode.substring(0, tosStart) + newTosSections + tosCode.substring(tosEnd);
  fs.writeFileSync('src/components/TermsOfService.tsx', tosCode);
  console.log("Patched TOS");
}


// Patch PrivacyPolicy.tsx
let ppCode = fs.readFileSync('src/components/PrivacyPolicy.tsx', 'utf8');

const newPpSections = `  const sections = [
    {
      id: "information-collection",
      title: "Information Collection",
      content: (
        <>
          <p>
            We collect several different types of information for various purposes to provide and improve our Service to you.
          </p>
          <ul className="list-disc pl-5 mt-4 space-y-2 text-[#8a8a8a]">
            <li><strong>Personal Data:</strong> While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you, such as your email address and name.</li>
            <li><strong>Usage Data:</strong> We may also collect information on how the Service is accessed and used. This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, and the time and date of your visit.</li>
            <li><strong>Project Data:</strong> The prompts you enter, the scripts generated, and the structure of your Roblox projects that are synced with Atmos Orbit are processed by our servers to provide the AI generation features.</li>
          </ul>
        </>
      )
    },
    {
      id: "use-of-data",
      title: "Use of Data",
      content: (
        <>
          <p>Atmos Orbit uses the collected data for various purposes:</p>
          <ul className="list-disc pl-5 mt-4 space-y-2 text-[#8a8a8a]">
            <li>To provide and maintain the Service</li>
            <li>To notify you about changes to our Service</li>
            <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
            <li>To provide customer care and support</li>
            <li>To provide analysis or valuable information so that we can improve the Service</li>
            <li>To monitor the usage of the Service and detect, prevent and address technical issues</li>
          </ul>
        </>
      )
    },
    {
      id: "data-security",
      title: "Data Security",
      content: (
        <p>
          The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data and Project Data, we cannot guarantee its absolute security. We encrypt sensitive data such as connection PINs and use secure protocols for our Studio plugin communication.
        </p>
      )
    },
    {
      id: "service-providers",
      title: "Service Providers",
      content: (
        <p>
          We may employ third party companies and individuals to facilitate our Service ("Service Providers"), to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used. These third parties (such as OpenAI, Anthropic, or Google Cloud) may have access to your Project Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
        </p>
      )
    },
    {
      id: "contact-us",
      title: "Contact Us",
      content: (
        <p>
          If you have any questions about this Privacy Policy, please contact us at privacy@atmosorbit.com.
        </p>
      )
    }
  ];`;

const ppStart = ppCode.indexOf('  const sections = [');
const ppEnd = ppCode.indexOf('  ];\n\n  return (', ppStart) + 4;

if (ppStart !== -1 && ppEnd !== -1) {
  ppCode = ppCode.substring(0, ppStart) + newPpSections + ppCode.substring(ppEnd);
  fs.writeFileSync('src/components/PrivacyPolicy.tsx', ppCode);
  console.log("Patched PP");
}
