import React from 'react';
import { LegalPage } from './LegalPage';

interface Props {
  onNavigate: (view: 'landing' | 'app' | 'privacy' | 'terms' | 'blog' | 'pricing' | 'auth') => void;
}

export function TermsOfService({ onNavigate }: Props) {
  const intro = (
    <p>
      Welcome to Atmos Orbit ("we," "our," or "us"). Please read these Terms of Service ("Terms") carefully before using our website, plugins, and AI generation services located at atmosorbit.com. By accessing or using the Service, you agree to be bound by these Terms. If you disagree with any part of the terms, you may not access the Service.
    </p>
  );

  const sections = [
    {
      id: "eligibility",
      title: "Eligibility",
      content: (
        <p>
          By using this Service, you represent and warrant that you are at least 13 years of age (or the age of majority in your jurisdiction) and have the full legal authority to enter into these Terms. If you are under the age of majority, you must have your parent or legal guardian's permission to use the Service.
        </p>
      )
    },
    {
      id: "user-accounts",
      title: "User Accounts",
      content: (
        <>
          <p>
            When you create an account with us, you must provide accurate, complete, and current information. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account on our Service.
          </p>
          <ul className="list-disc pl-5 mt-4 space-y-2 text-[#8a8a8a]">
            <li>You are responsible for safeguarding the password and PINs that you use to access the Service and for any activities or actions under your password.</li>
            <li>You agree not to disclose your password or PINs to any third party.</li>
            <li>You must notify us immediately upon becoming aware of any breach of security or unauthorized use of your account.</li>
          </ul>
        </>
      )
    },
    {
      id: "intellectual-property",
      title: "Intellectual Property",
      content: (
        <>
          <p>
            The Service and its original content, features, and functionality (excluding AI-generated code produced for your projects) are and will remain the exclusive property of Atmos Orbit and its licensors. Our trademarks and trade dress may not be used in connection with any product or service without our prior written consent.
          </p>
          <p>
            <strong>Generated Code & Assets:</strong> Any code, scripts (such as Luau), or integrated assets generated by Atmos Orbit in response to your prompts belong to you, subject to Roblox's terms of service and the licensing of any third-party Creator Marketplace assets fetched by the tool.
          </p>
        </>
      )
    },
    {
      id: "prohibited-uses",
      title: "Prohibited Uses",
      content: (
        <p>
          You agree not to use the Service: (a) in any way that violates any applicable national or international law or regulation; (b) for the purpose of exploiting, harming, or attempting to exploit or harm minors in any way; (c) to generate malicious code, exploits, or scripts designed to harm, disrupt, or gain unauthorized access to Roblox games or servers; or (d) to impersonate or attempt to impersonate Atmos Orbit, an employee, another user, or any other person or entity.
        </p>
      )
    },
    {
      id: "contact-us",
      title: "Contact Us",
      content: (
        <p>
          If you have any questions about these Terms, please contact us at legal@atmosorbit.com.
        </p>
      )
    }
  ];

  return (
    <LegalPage
      title="Terms of Service"
      lastUpdated="August 12, 2026"
      readingTime="5 min"
      intro={intro}
      sections={sections}
      onNavigate={onNavigate}
    />
  );
}
